server:
  port: 9527
spring:
  application:
    name: servicecloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId: servicecloud-dept
    mydept.path: /mydept/**
  ignore-local-service: true
  ignored-services: "*" #servicecloud-dept
  prefix: /xu


